"""Exp 52 — Pool-separation rerun (R12-R17 W12).

Concern: the original Exp 10 cached `sample_extend_50` verdicts were
generated by the v20 scaffolded solver, which selects same-domain
exemplars from the *evaluation pool's other pids* at solve time.
Symmetry between base and ext is the paper's defence; the reviewers
have repeatedly noted that interactions with the added wisdom can
break that symmetry.

This experiment regenerates base + ext answers for the 3 KEEPs
(W076, W077, W078) on the same 50 cached pids using a *clean*
solver with NO same-domain exemplar retrieval (the same Exp 47-style
solver: frame + rewritten_problem + wisdom_block). We then re-judge
with the 3-family cheap panel and compare to the original cached
verdicts (Exp 36 re-judgment of v20 answers, plus Exp 35 expensive).

If wr_ext under the clean (no-exemplar) protocol is comparable to
original cached wr_ext, exemplar contamination does NOT drive the
inner-loop signal. If wr_ext shifts substantially (e.g. drops below
0.50), the original signal was partly an exemplar interaction.

This is the same protocol Exp 47 already used on fresh pids; we
extend it to the original 50 cached pids so the pool-separation
question is answered on the EXACT pids the original verdicts
contested.

Cost: 50 pids × 2 conditions × 3 KEEPs = 300 generations; 3 judges
× 300 pairs = 900 judge calls. ~$15 cheap-tier.
"""
import json
import os
import random
import re
import sys
import time
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

PROJECT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT / "phase zero" / "scripts"))


def _load_api_keys():
    if os.environ.get("RUOLI_GPT_KEY") and os.environ.get("RUOLI_BASE_URL"):
        return
    keyfile = Path.home() / ".api_keys"
    if not keyfile.exists():
        return
    pat = re.compile(r'^\s*export\s+(\w+)=("([^"]*)"|\'([^\']*)\'|(\S+))')
    for line in keyfile.read_text().splitlines():
        m = pat.match(line)
        if not m: continue
        name = m.group(1)
        val = m.group(3) if m.group(3) is not None else (
              m.group(4) if m.group(4) is not None else m.group(5))
        os.environ.setdefault(name, val)
        if name == "RUOLI_BASE_URL":
            base = val + "/v1" if not val.endswith("/v1") else val
            os.environ.setdefault("CLAUDE_PROXY_BASE_URL", base)
            os.environ.setdefault("GPT5_BASE_URL", base)
            os.environ.setdefault("GEMINI_PROXY_BASE_URL", base)
        if name == "RUOLI_GEMINI_KEY":
            os.environ.setdefault("GEMINI_PROXY_API_KEY", val)
        if name == "RUOLI_GPT_KEY":
            os.environ.setdefault("GPT5_API_KEY", val)
        if name == "RUOLI_CLAUDE_KEY":
            os.environ.setdefault("CLAUDE_PROXY_API_KEY", val)

_load_api_keys()
from model_router import cheap, cheap_panel
from llm_client import parse_json_from_llm

CACHE = PROJECT / "phase two" / "analysis" / "cache"
AUTO = PROJECT / "phase four" / "autonomous"
OUT_LOG = AUTO / "exp52_pool_separation_log.json"

PARALLEL = 6

KEEPS_INFO = [
    {"tid": "W076", "aphorism": "穷则变，变则通，通则久",
     "unpacked_for_llm": "面对僵局或困境时，先承认当前路径已经走不通，主动寻找另一种思路或形式；变化本身不是目的，但常是打破僵局的必要条件。"},
    {"tid": "W077", "aphorism": "没有调查，就没有发言权",
     "unpacked_for_llm": "在做判断前，先确认自己拥有判断所需的事实基础——具体的、第一手的、足以区分不同假设的信息；缺乏调查的意见多半是空话。"},
    {"tid": "W078", "aphorism": "是骡子是马，拉出来遛遛",
     "unpacked_for_llm": "纸上的定性争论再激烈，不如设计一个能区分两方说法的实际测试；让现实而不是话语去决定哪一方更接近真相。"},
]

FRAME_PROMPT = """对下面问题产生 frame + 重写。

## 原题
{problem}

## 输出 JSON
{{"frame": "object_level/paradigm/hybrid",
  "critical_reframe": "30-80字",
  "rewritten_problem": "120-250字"}}
"""

EXECUTE_PROMPT = """# 解决问题

## PRIMARY FRAME
- frame: {frame}
- critical reframe: {critical_reframe}

## 问题（重写）
{rewritten_problem}

## 次要参考 wisdom
{wisdom_block}

## 要求：≤ 500 字
开始："""

JUDGE_PROMPT = """方法论评审.

## 问题
{problem}

## 解答 A
{answer_a}

## 解答 B
{answer_b}

Output JSON: {{"winner": "A"/"B"/"tie", "score_a": 1-10, "score_b": 1-10,
  "reasoning": "80 chars max"}}
"""


def solve(client, problem, wisdom):
    try:
        r = client.generate(FRAME_PROMPT.format(problem=problem),
                            max_tokens=500, temperature=0.2)
        m = parse_json_from_llm(r["text"])
    except Exception as e:
        return f"[turn0 err: {e}]"
    if wisdom:
        wb = f"• {wisdom['aphorism']}: {wisdom.get('unpacked_for_llm', '')[:200]}"
    else:
        wb = "(无)"
    try:
        r = client.generate(EXECUTE_PROMPT.format(
            frame=m.get("frame", "object_level"),
            critical_reframe=m.get("critical_reframe", ""),
            rewritten_problem=m.get("rewritten_problem", problem),
            wisdom_block=wb), max_tokens=900, temperature=0.2)
        return r["text"].strip()
    except Exception as e:
        return f"[turn1 err: {e}]"


def judge_one(client, problem, a, b):
    try:
        r = client.generate(JUDGE_PROMPT.format(problem=problem,
                                                  answer_a=a, answer_b=b),
                            max_tokens=300, temperature=0.0)
        v = parse_json_from_llm(r["text"])
        return v.get("winner", "tie")
    except Exception:
        return "err"


def main():
    eval_set = json.loads((CACHE / "sample_extend_50.json").read_text())
    eval_set = [p for p in eval_set if "description" in p]
    pids = [p["problem_id"] for p in eval_set]
    pid_to_prob = {p["problem_id"]: p["description"] for p in eval_set}
    print(f"Eval set (sample_extend_50): {len(eval_set)} pids")

    solver = cheap("gemini")
    judges = cheap_panel()
    print(f"Solver: {solver.model}, judges: {[j.family for j in judges]}\n")

    # Step 1: generate base (no wisdom) + ext (with wisdom) for each KEEP
    # Without same-domain exemplars (clean Exp-47-style solver).
    print(f"[1/3] Generating clean base answers (no wisdom, no exemplar)...")
    base_answers = {}
    t0 = time.time()
    with ThreadPoolExecutor(max_workers=PARALLEL) as ex:
        futs = {ex.submit(solve, solver, pid_to_prob[pid], None): pid
                  for pid in pids}
        for i, f in enumerate(as_completed(futs), 1):
            pid = futs[f]
            base_answers[pid] = f.result()
            if i % 10 == 0:
                print(f"  base {i}/{len(pids)} ({time.time() - t0:.0f}s)")

    print(f"\n[2/3] Generating clean ext answers (per KEEP, no exemplar)...")
    ext_answers = {k["tid"]: {} for k in KEEPS_INFO}
    tasks = [(k, pid) for k in KEEPS_INFO for pid in pids]
    t0 = time.time()
    with ThreadPoolExecutor(max_workers=PARALLEL) as ex:
        futs = {ex.submit(solve, solver, pid_to_prob[pid], k): (k["tid"], pid)
                  for k, pid in tasks}
        for i, f in enumerate(as_completed(futs), 1):
            tid, pid = futs[f]
            ext_answers[tid][pid] = f.result()
            if i % 25 == 0:
                print(f"  ext {i}/{len(tasks)} ({time.time() - t0:.0f}s)")

    # Step 2: judge each (KEEP, pid) under all 3 cheap families
    print(f"\n[3/3] Judging across 3 cheap families...")
    verdicts = {k["tid"]: {j.family: {} for j in judges} for k in KEEPS_INFO}
    jtasks = [(j, k["tid"], pid)
                for j in judges for k in KEEPS_INFO for pid in pids]

    def jt(judge, tid, pid):
        b = base_answers.get(pid, "")
        e = ext_answers[tid].get(pid, "")
        if not b or not e or b.startswith("[") or e.startswith("["):
            return judge.family, tid, pid, "missing"
        rng = random.Random((hash(pid) ^ hash(tid)) % (2**32))
        if rng.random() < 0.5:
            left, right, ext_was = e, b, "A"
        else:
            left, right, ext_was = b, e, "B"
        w = judge_one(judge, pid_to_prob[pid], left, right)
        if w == "tie": v = "tie"
        elif w in ("A", "B"): v = "ext" if w == ext_was else "base"
        else: v = "err"
        return judge.family, tid, pid, v

    t0 = time.time()
    with ThreadPoolExecutor(max_workers=PARALLEL) as ex:
        futs = [ex.submit(jt, j, t, p) for (j, t, p) in jtasks]
        for i, f in enumerate(as_completed(futs), 1):
            fam, tid, pid, v = f.result()
            verdicts[tid][fam][pid] = v
            if i % 50 == 0:
                print(f"  judge {i}/{len(jtasks)} ({time.time() - t0:.0f}s)")

    # Aggregate
    print(f"\n=== Pool-separation results (no eval-pool exemplars) ===")
    print(f"{'KEEP':5s} {'judge':14s} {'ext':>4s} {'base':>5s} {'tie':>4s} "
          f"{'n_eff':>6s} {'wr_ext':>7s}")
    print("-" * 60)
    summary = {}
    for k in KEEPS_INFO:
        summary[k["tid"]] = {}
        for j in judges:
            v = verdicts[k["tid"]][j.family]
            ne = sum(1 for x in v.values() if x == "ext")
            nb = sum(1 for x in v.values() if x == "base")
            nt = sum(1 for x in v.values() if x == "tie")
            tot = ne + nb
            wr = ne / tot if tot else 0.5
            summary[k["tid"]][j.family] = {"ext": ne, "base": nb, "tie": nt,
                                            "n_eff": tot, "wr_ext": wr}
            print(f"{k['tid']:5s} {j.family:14s} {ne:>4d} {nb:>5d} {nt:>4d} "
                  f"{tot:>6d} {wr:>7.3f}")

    # Compare to cached with-exemplar verdicts
    print(f"\n=== Comparison to original cached (Exp 36, v20 with exemplars) ===")
    print(f"{'KEEP':5s} {'judge':14s} {'cached wr':>10s} "
          f"{'no-exemplar wr':>15s} {'delta':>7s}")
    print("-" * 60)
    e36 = json.loads((AUTO / "exp36_cheap_verdicts_log.json").read_text())
    cached_wrs = {}
    for r in e36["results"]:
        if r["cand_id"] in summary:
            cached_wrs[r["cand_id"]] = {}
            for fam, vd in r["verdicts"].items():
                e = sum(1 for x in vd.values() if x == "ext")
                b = sum(1 for x in vd.values() if x == "base")
                cached_wrs[r["cand_id"]][fam] = e / (e + b) if (e + b) else 0.5

    for k in KEEPS_INFO:
        for j in judges:
            cw = cached_wrs.get(k["tid"], {}).get(j.family, None)
            nw = summary[k["tid"]][j.family]["wr_ext"]
            if cw is not None:
                d = nw - cw
                print(f"{k['tid']:5s} {j.family:14s} {cw:>10.3f} "
                      f"{nw:>15.3f} {d:>+7.3f}")

    out = {"timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
           "n_pids": len(pids),
           "solver": "gemini cheap, no same-domain exemplar (Exp 47-style)",
           "summary": summary,
           "verdicts_per_pid": verdicts}
    OUT_LOG.write_text(json.dumps(out, ensure_ascii=False, indent=2))
    print(f"\nSaved → {OUT_LOG.name}")


if __name__ == "__main__":
    main()
