"""Target-free metadata for preregistered M3 shrink step 4.

The child changes exactly one old-DSL structural limit: after the inherited
AND normalization (flatten, canonical sort, and deduplication), a canonical
top-level conjunction may contain at most two clauses instead of three.
Every registry allocation, type rule, operator meaning, CBOR byte identity,
AST hash, and MDL rule is inherited unchanged from shrink step 3.
"""

from __future__ import annotations

from typing import Final

from .phase3_m3_shrink3_core_v1 import (
    ACTIVE_AGGREGATE_IDS,
    ACTIVE_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_NAMES,
    ACTIVE_FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_IDS,
    ACTIVE_RATIONAL_PARAMETER_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_ALLOCATED_ID_COUNT,
    BINARY_OPERATOR_CODE_SPACE_SIZE,
    BINARY_OPERATOR_CODE_WIDTH_BITS,
    BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_REGISTRY_NAMESPACE,
    FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    LEGAL_AST_TOMBSTONE_PRIORITY,
    POST_TOMBSTONE_VALIDATION_STAGES,
    PRE_TOMBSTONE_VALIDATION_STAGES,
    REMOVED_AGGREGATE_ERROR,
    REMOVED_BINARY_OPERATOR_ERROR,
    REMOVED_RATIONAL_PARAMETER_ERROR,
    RESERVED_BINARY_OPERATOR_IDS,
    RESERVED_FORMAL_BINARY_OPERATOR_ERROR,
    RESERVED_RATIONAL_PARAMETER_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_NAMES,
    TOMBSTONED_AGGREGATE_IDS,
    TOMBSTONED_BINARY_OPERATOR_IDS,
    TOMBSTONED_BINARY_OPERATOR_NAMES,
    TOMBSTONED_RATIONAL_PARAMETER_IDS,
    UNALLOCATED_BINARY_OPERATOR_REGISTRY_ERROR,
    UNKNOWN_SOURCE_OPERATOR_NAME_ERROR,
)


PARENT_DSL_VERSION: Final = "hegel-old-dsl-v1.3.0"
PARENT_FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.3.0"
PARENT_DIAGNOSTIC_RESULT_COMMIT: Final = (
    "c286732c140bd9adcfd3eef2b1788b3eac0eb3e9"
)
PARENT_DIAGNOSTIC_IMPLEMENTATION_BASIS: Final = (
    "d17b03e14f3f3e8a63c924706086f17367fbc0d6"
)
PARENT_DIAGNOSTIC_EVIDENCE_RECORD_ID: Final = (
    "phase3_shrink3_dual_complete_enumeration_diagnostic_"
    "3030ad10f2cd4f767a8397597be1ab3ed6cac7cd71975d69f59cc5abec6a4f5a"
)
PARENT_DIAGNOSTIC_STATUS: Final = "DUAL_DSL_TOO_LARGE_HOST_REPLAY_PASS"
PARENT_DIAGNOSTIC_CLAIM_LEVEL: Final = "NON_FORMAL_DUAL_CHILD_DIAGNOSTIC"

DSL_VERSION: Final = "hegel-old-dsl-v1.4.0"
FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.4.0"
HUMAN_AMENDMENT_ID: Final = "hegel-freeze-p2b-p3-v1.4.0-shrink-step4"
SHRINK_STEP_ID: Final = "SHRINK_STEP_4_REDUCE_MAX_TOP_LEVEL_CLAUSES_3_TO_2"
SEALED_DUAL_STRICT_OUTCOME_REPLAY_STATUS: Final = "NOT_RUN"

PARENT_MAX_TOP_LEVEL_CLAUSES: Final = 3
MAX_TOP_LEVEL_CLAUSES: Final = 2
STRUCTURAL_LIMIT_ERROR: Final = "REJECT_STRUCTURAL_LIMIT"
TOP_LEVEL_AND_NORMALIZATION_ORDER: Final = (
    "NORMALIZE_CHILDREN",
    "FLATTEN",
    "CANONICAL_CBOR_SORT",
    "DEDUPLICATE",
    "AND0_REJECT_AND1_ELIMINATE",
    "ENFORCE_MAX_TOP_LEVEL_CLAUSES_2",
)


__all__ = [name for name in globals() if name.isupper()]
