"""Target-free metadata for preregistered M3 shrink step 6.

The child changes exactly one old-DSL structural limit: a normalized canonical
AST may have depth at most three instead of four.  The six-node and two-clause
limits, registries, typing, semantics, canonical bytes, hashes, and MDL rules
remain inherited unchanged.
"""

from __future__ import annotations

from typing import Final

from .phase3_m3_shrink5_core_v1 import (
    ACTIVE_AGGREGATE_IDS,
    ACTIVE_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_NAMES,
    ACTIVE_FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_IDS,
    ACTIVE_RATIONAL_PARAMETER_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_ALLOCATED_ID_COUNT,
    BINARY_OPERATOR_CODE_SPACE_SIZE,
    BINARY_OPERATOR_CODE_WIDTH_BITS,
    BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_REGISTRY_NAMESPACE,
    FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    LEGAL_AST_TOMBSTONE_PRIORITY,
    MAXIMUM_AST_NODE_COUNT,
    MAX_TOP_LEVEL_CLAUSES,
    MAX_TOTAL_NODE_COUNT,
    POST_TOMBSTONE_VALIDATION_STAGES,
    PRE_TOMBSTONE_VALIDATION_STAGES,
    REMOVED_AGGREGATE_ERROR,
    REMOVED_BINARY_OPERATOR_ERROR,
    REMOVED_RATIONAL_PARAMETER_ERROR,
    RESERVED_BINARY_OPERATOR_IDS,
    RESERVED_FORMAL_BINARY_OPERATOR_ERROR,
    RESERVED_RATIONAL_PARAMETER_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_NAMES,
    TOMBSTONED_AGGREGATE_IDS,
    TOMBSTONED_BINARY_OPERATOR_IDS,
    TOMBSTONED_BINARY_OPERATOR_NAMES,
    TOMBSTONED_RATIONAL_PARAMETER_IDS,
    UNALLOCATED_BINARY_OPERATOR_REGISTRY_ERROR,
    UNKNOWN_SOURCE_OPERATOR_NAME_ERROR,
)


PARENT_DSL_VERSION: Final = "hegel-old-dsl-v1.5.0"
PARENT_FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.5.0"
PARENT_DIAGNOSTIC_RESULT_COMMIT: Final = (
    "5bfe8474ca63abbadb1d3484a51ce3012081dfb3"
)
PARENT_DIAGNOSTIC_IMPLEMENTATION_BASIS: Final = (
    "a3c384b4cb0f95583af6a1eb1c1d256ef6e9128a"
)
PARENT_DIAGNOSTIC_EVIDENCE_RECORD_ID: Final = (
    "phase3_shrink5_dual_complete_enumeration_diagnostic_"
    "f33b86f3fbab70acb7d8e61fa47f59568a0d56c884c4cf75dfef961cc73dd34b"
)
PARENT_DIAGNOSTIC_ARTIFACT_PATH: Final = (
    "Hegel Machine/artifacts/phase3_shrink5_dual_complete_enumeration_"
    "diagnostic_v1.json"
)
PARENT_DIAGNOSTIC_ARTIFACT_SHA256: Final = (
    "99a799e34876754a8f938f8e25f756992d0784b03bae398b1434e57320b80c82"
)
PARENT_DIAGNOSTIC_STATUS: Final = "DUAL_DSL_TOO_LARGE_HOST_REPLAY_PASS"
PARENT_DIAGNOSTIC_CLAIM_LEVEL: Final = "NON_FORMAL_DUAL_CHILD_DIAGNOSTIC"

DSL_VERSION: Final = "hegel-old-dsl-v1.6.0"
FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.6.0"
HUMAN_AMENDMENT_ID: Final = "hegel-freeze-p2b-p3-v1.6.0-shrink-step6"
SHRINK_STEP_ID: Final = "SHRINK_STEP_6_REDUCE_MAX_TOTAL_AST_DEPTH_4_TO_3"
SEALED_DUAL_STRICT_OUTCOME_REPLAY_STATUS: Final = "NOT_RUN"

PARENT_MAX_TOTAL_AST_DEPTH: Final = 4
MAX_TOTAL_AST_DEPTH: Final = 3
MAXIMUM_AST_DEPTH: Final = MAX_TOTAL_AST_DEPTH
STRUCTURAL_LIMIT_ERROR: Final = "REJECT_STRUCTURAL_LIMIT"
NORMALIZATION_BEFORE_DEPTH_LIMIT_ORDER: Final = (
    "PARENT_SOURCE_PARSE_TYPE_REGISTRY_AND_NORMALIZATION",
    "ENFORCE_INHERITED_MAX_TOP_LEVEL_CLAUSES_2",
    "ENFORCE_INHERITED_MAX_TOTAL_NODE_COUNT_6",
    "ENFORCE_MAX_TOTAL_AST_DEPTH_3",
)


__all__ = [name for name in globals() if name.isupper()]
