"""Target-free metadata for preregistered M3 shrink step 5.

The child changes exactly one old-DSL structural limit: a normalized canonical
AST may contain at most six nodes instead of seven.  The inherited two-clause
top-level conjunction limit and every registry allocation, type rule, operator
meaning, CBOR byte identity, AST hash, and MDL rule remain unchanged.
"""

from __future__ import annotations

from typing import Final

from .phase3_m3_shrink4_core_v1 import (
    ACTIVE_AGGREGATE_IDS,
    ACTIVE_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_NAMES,
    ACTIVE_FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    ACTIVE_FORMAL_BINARY_OPERATOR_IDS,
    ACTIVE_RATIONAL_PARAMETER_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_IDS,
    ACTIVE_SOURCE_BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_ALLOCATED_ID_COUNT,
    BINARY_OPERATOR_CODE_SPACE_SIZE,
    BINARY_OPERATOR_CODE_WIDTH_BITS,
    BINARY_OPERATOR_NAMES,
    BINARY_OPERATOR_REGISTRY_NAMESPACE,
    FORMAL_CANONICAL_BINARY_OPERATOR_IDS,
    LEGAL_AST_TOMBSTONE_PRIORITY,
    POST_TOMBSTONE_VALIDATION_STAGES,
    PRE_TOMBSTONE_VALIDATION_STAGES,
    REMOVED_AGGREGATE_ERROR,
    REMOVED_BINARY_OPERATOR_ERROR,
    REMOVED_RATIONAL_PARAMETER_ERROR,
    RESERVED_BINARY_OPERATOR_IDS,
    RESERVED_FORMAL_BINARY_OPERATOR_ERROR,
    RESERVED_RATIONAL_PARAMETER_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_IDS,
    SOURCE_ALIAS_BINARY_OPERATOR_NAMES,
    TOMBSTONED_AGGREGATE_IDS,
    TOMBSTONED_BINARY_OPERATOR_IDS,
    TOMBSTONED_BINARY_OPERATOR_NAMES,
    TOMBSTONED_RATIONAL_PARAMETER_IDS,
    UNALLOCATED_BINARY_OPERATOR_REGISTRY_ERROR,
    UNKNOWN_SOURCE_OPERATOR_NAME_ERROR,
    MAX_TOP_LEVEL_CLAUSES as PARENT_MAX_TOP_LEVEL_CLAUSES,
)


PARENT_DSL_VERSION: Final = "hegel-old-dsl-v1.4.0"
PARENT_FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.4.0"
PARENT_DIAGNOSTIC_RESULT_COMMIT: Final = (
    "1bbdae8f3131625621c0bc1cfdfe5d7da6035e13"
)
PARENT_DIAGNOSTIC_IMPLEMENTATION_BASIS: Final = (
    "103eb6ad2d8500024580193b895809784d894609"
)
PARENT_DIAGNOSTIC_EVIDENCE_RECORD_ID: Final = (
    "phase3_shrink4_dual_complete_enumeration_diagnostic_"
    "5693b38315689969a1a525b75bec2917f95af1aa54951267797a0319afc60521"
)
PARENT_DIAGNOSTIC_ARTIFACT_PATH: Final = (
    "Hegel Machine/artifacts/phase3_shrink4_dual_complete_enumeration_"
    "diagnostic_v1.json"
)
PARENT_DIAGNOSTIC_ARTIFACT_SHA256: Final = (
    "2d653f667d8d43e0e8e68c54d6f0a939aab57bf6ba3add9b334809ca17745058"
)
PARENT_DIAGNOSTIC_STATUS: Final = "DUAL_DSL_TOO_LARGE_HOST_REPLAY_PASS"
PARENT_DIAGNOSTIC_CLAIM_LEVEL: Final = "NON_FORMAL_DUAL_CHILD_DIAGNOSTIC"

DSL_VERSION: Final = "hegel-old-dsl-v1.5.0"
FREEZE_VERSION: Final = "hegel-freeze-p2b-p3-v1.5.0"
HUMAN_AMENDMENT_ID: Final = "hegel-freeze-p2b-p3-v1.5.0-shrink-step5"
SHRINK_STEP_ID: Final = "SHRINK_STEP_5_REDUCE_MAX_TOTAL_NODE_COUNT_7_TO_6"
SEALED_DUAL_STRICT_OUTCOME_REPLAY_STATUS: Final = "NOT_RUN"

PARENT_MAX_TOTAL_NODE_COUNT: Final = 7
MAX_TOTAL_NODE_COUNT: Final = 6
MAXIMUM_AST_NODE_COUNT: Final = MAX_TOTAL_NODE_COUNT
MAX_TOP_LEVEL_CLAUSES: Final = PARENT_MAX_TOP_LEVEL_CLAUSES
STRUCTURAL_LIMIT_ERROR: Final = "REJECT_STRUCTURAL_LIMIT"
NORMALIZATION_BEFORE_NODE_LIMIT_ORDER: Final = (
    "NORMALIZE_CHILDREN",
    "FLATTEN",
    "CANONICAL_CBOR_SORT",
    "DEDUPLICATE",
    "AND0_REJECT_AND1_ELIMINATE",
    "ENFORCE_INHERITED_MAX_TOP_LEVEL_CLAUSES_2",
    "ENFORCE_MAX_TOTAL_NODE_COUNT_6",
)


__all__ = [name for name in globals() if name.isupper()]
